import type { ICat, ICatBreedType, ICatLocationType, ICoatType, IColor } from "./model";

const catColors: IColor[] = [
    { id: 1, name: "Черный", rgb: "rgb(0, 0, 0)", comment: "Сплошной черный окрас", date: "2025-04-07" },
    { id: 2, name: "Белый", rgb: "rgb(255, 255, 255)", comment: "Чисто белый окрас", date: "2025-04-07" },
    { id: 3, name: "Рыжий", rgb: "rgb(255, 140, 0)", comment: "Ярко-оранжевый, классический рыжий", date: "2025-04-07" },
    { id: 4, name: "Голубой (серый)", rgb: "rgb(110, 123, 139)", comment: "Серо-голубой, часто называется голубым", date: "2025-04-07" },
    { id: 5, name: "Кремовый", rgb: "rgb(252, 230, 201)", comment: "Светло-кремовый, пастельный", date: "2025-04-07" },
    { id: 6, name: "Шоколадный", rgb: "rgb(75, 46, 30)", comment: "Темно-коричневый, цвет молочного шоколада", date: "2025-04-07" },
    { id: 7, name: "Лиловый", rgb: "rgb(181, 157, 187)", comment: "Светло-фиолетовый с серым оттенком", date: "2025-04-07" },
    { id: 8, name: "Циннамон", rgb: "rgb(160, 82, 45)", comment: "Красно-коричневый, цвет корицы", date: "2025-04-07" },
    { id: 9, name: "Фавн", rgb: "rgb(229, 170, 112)", comment: "Светло-олений, палевый", date: "2025-04-07" },
    { id: 10, name: "Черепаховый", rgb: "rgb(123, 63, 0)", comment: "Смесь черного и рыжего, базовый темный", date: "2025-04-07" },
    { id: 11, name: "Калико", rgb: "rgb(255, 255, 255)", comment: "Трехцветный: белый с рыжими и черными пятнами", date: "2025-04-07" },
    { id: 12, name: "Табби", rgb: "rgb(139, 125, 107)", comment: "Полосатый, теплый серо-коричневый", date: "2025-04-07" },
    { id: 13, name: "Биколор", rgb: "rgb(255, 255, 255)", comment: "Двухцветный: белый в сочетании с другим", date: "2025-04-07" },
    { id: 14, name: "Колор-поинт", rgb: "rgb(242, 232, 220)", comment: "Светлое тело с темными конечностями", date: "2025-04-07" },
    { id: 15, name: "Серебристый", rgb: "rgb(192, 192, 192)", comment: "Металлический серый", date: "2025-04-07" },
    { id: 16, name: "Золотистый", rgb: "rgb(218, 165, 32)", comment: "Теплый золотой", date: "2025-04-07" },
    { id: 17, name: "Голубой крем", rgb: "rgb(176, 168, 185)", comment: "Смесь голубого и кремового", date: "2025-04-07" },
    { id: 18, name: "Соболиный", rgb: "rgb(62, 39, 35)", comment: "Очень темный коричневый, почти черный", date: "2025-04-07" },
    { id: 19, name: "Дымчатый", rgb: "rgb(112, 128, 144)", comment: "Серо-синий, с эффектом дымки", date: "2025-04-07" },
    { id: 20, name: "Тигровый", rgb: "rgb(205, 133, 63)", comment: "Рыже-коричневый с полосами", date: "2025-04-07" }
];

const catCoatTypes: ICoatType[] = [
    { id: 1, name: "Длинношерстная", comment: "Длина шерсти более 5 см, густой подшерсток", date: "2025-04-07" },
    { id: 2, name: "Полудлинношерстная", comment: "Шерсть средней длины, часто с воротником и штанишками", date: "2025-04-07" },
    { id: 3, name: "Короткошерстная", comment: "Короткая, плотно прилегающая шерсть", date: "2025-04-07" },
    { id: 4, name: "Жесткошерстная", comment: "Проволочная, упругая шерсть, часто курчавая", date: "2025-04-07" },
    { id: 5, name: "Бесшерстная", comment: "Отсутствие шерсти или очень тонкий пух (сфинксы)", date: "2025-04-07" }
];

const catBreeds: ICatBreedType[] = [
    { id: 1, name: "Британская короткошерстная", comment: "Плюшевая шерсть, спокойный и независимый характер" },
    { id: 2, name: "Шотландская вислоухая", comment: "Загнутые вперёд уши, дружелюбная и мягкая" },
    { id: 3, name: "Мейн-кун", comment: "Крупная порода, общительная, с кисточками на ушах" },
    { id: 4, name: "Персидская", comment: "Длинная шерсть, спокойный и ласковый нрав" },
    { id: 5, name: "Сиамская", comment: "Голубые глаза, окрас колор-поинт, разговорчивая" },
    { id: 6, name: "Канадский сфинкс", comment: "Бесшёрстная, тёплая на ощупь, очень привязчивая" },
    { id: 7, name: "Русская голубая", comment: "Серебристо-голубая шерсть, тихая и умная" },
    { id: 8, name: "Бенгальская", comment: "Леопардовый окрас, активная и игривая" },
    { id: 9, name: "Абиссинская", comment: "Тикированный окрас, энергичная и любопытная" },
    { id: 10, name: "Ориентальная", comment: "Утончённая, с большими ушами, очень общительная" },
    { id: 11, name: "Норвежская лесная", comment: "Густая водонепроницаемая шерсть, выносливая" },
    { id: 12, name: "Сибирская", comment: "Полудлинная шерсть, гипоаллергенная, преданная" },
    { id: 13, name: "Рэгдолл", comment: "Крупная, расслабленная, «тряпичная кукла» на руках" },
    { id: 14, name: "Бирманская", comment: "Белые «носочки», сапфировые глаза, нежная" },
    { id: 15, name: "Турецкая ангора", comment: "Элегантная, с пушистым хвостом, игривая" }
];

const catLocationType: ICatLocationType[] = [
    { id: 1, name: "Уличный" },
    { id: 2, name: "Домашний" }
]

const cats: ICat[] = [
    {
        id: 1,
        name: "Барсик",
        shortName: "Барс",
        coatTypeId: 3,
        owner: "Иван",
        mass: 4.2,
        date: "2025-01-15",
        colorId: 3,
        locationTypeId: 2,
        breedTypeId: 1,
        softness: "средняя",
        breadness: true,
        bigeyedness: 7,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Barsik/photo1.jpg",
            "https://ik.imagekit.io/tema13/Barsik/photo2.jpg",
            "https://ik.imagekit.io/tema13/Barsik/photo3.jpg"
        ]
    },
    {
        id: 2,
        name: "Каспер",
        shortName: "Каспер",
        coatTypeId: 2,
        owner: "Артём",
        mass: 4.4,
        date: "2025-08-24",
        colorId: 19,
        locationTypeId: 2,
        breedTypeId: 7,
        softness: "мягкая булочка",
        breadness: true,
        bigeyedness: 9,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Kasper/photo1.jpg",
            "https://ik.imagekit.io/tema13/Kasper/photo2.jpg",
            "https://ik.imagekit.io/tema13/Kasper/photo3.jpg"
        ]
    },
    {
        id: 3,
        name: "Рыжик",
        shortName: "Рыж",
        coatTypeId: 1,
        owner: "Олег",
        mass: 5.5,
        date: "2025-03-10",
        colorId: 3,
        locationTypeId: 3,
        breedTypeId: 3,
        softness: "очень мягкая",
        breadness: true,
        bigeyedness: 8,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Rijick/photo1.jpg",
            "https://ik.imagekit.io/tema13/Rijick/photo2.jpg"
        ]
    },
    {
        id: 4,
        name: "Снежок",
        shortName: "Снеж",
        coatTypeId: 2,
        owner: "Мария",
        mass: 4.9,
        date: "2025-02-20",
        colorId: 2,
        locationTypeId: 1,
        breedTypeId: 4,
        softness: "мягкая",
        breadness: true,
        bigeyedness: 9,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Snejock/photo1.jpg",
            "https://ik.imagekit.io/tema13/Snejock/photo2.jpg",
            "https://ik.imagekit.io/tema13/Snejock/photo3.jpg"
        ]
    },
    {
        id: 5,
        name: "неизвестно",
        shortName: "неизвестно",
        coatTypeId: 3,
        owner: "Артур",
        mass: 6.0,
        date: "2025-04-01",
        colorId: 1,
        locationTypeId: 2,
        breedTypeId: 7,
        softness: "средняя",
        breadness: true,
        bigeyedness: 10,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Kot/photo1.jpg",
            "https://ik.imagekit.io/tema13/Kot/photo2.jpg",
            "https://ik.imagekit.io/tema13/Kot/photo3.jpg",
            "https://ik.imagekit.io/tema13/Kot/photo4.jpg",
            "https://ik.imagekit.io/tema13/Kot/photo5.jpg"
        ]
    },
    {
        id: 6,
        name: "Луна",
        shortName: "Луна",
        coatTypeId: 2,
        owner: "Елена",
        mass: 3.5,
        date: "2025-01-25",
        colorId: 1,
        locationTypeId: 2,
        breedTypeId: 7,
        softness: "мягкая",
        breadness: true,
        bigeyedness: 10,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Luna/photo1.jpg",
            "https://ik.imagekit.io/tema13/Luna/photo2.jpg",
            "https://ik.imagekit.io/tema13/Luna/photo3.jpg"
        ]
    },
    {
        id: 7,
        name: "Тиша",
        shortName: "Тиша",
        coatTypeId: 3,
        owner: "Дмитрий",
        mass: 3.1,
        date: "2025-03-05",
        colorId: 8,
        locationTypeId: 2,
        breedTypeId: 9,
        softness: "без шерсти",
        breadness: false,
        bigeyedness: 8,
        stars: 5,
        photos: [
            "https://ik.imagekit.io/tema13/Tisha/photo1.jpg",
            "https://ik.imagekit.io/tema13/Tisha/photo2.jpg",
            "https://ik.imagekit.io/tema13/Tisha/photo3.jpg"
        ]
    },
    {
        id: 8,
        name: "Василиса",
        shortName: "Вася",
        coatTypeId: 1,
        owner: "Ольга",
        mass: 4.7,
        date: "2025-02-14",
        colorId: 17,
        locationTypeId: 1,
        breedTypeId: 10,
        softness: "очень мягкая",
        breadness: true,
        bigeyedness: 9,
        stars: 5
    },
    {
        id: 9,
        name: "Персик",
        shortName: "Перс",
        coatTypeId: 3,
        owner: "Сергей",
        mass: 5.2,
        date: "2025-04-02",
        colorId: 15,
        locationTypeId: 1,
        breedTypeId: 11,
        softness: "средняя",
        breadness: true,
        bigeyedness: 7,
        stars: 5
    },
    {
        id: 10,
        name: "Черныш",
        shortName: "Черн",
        coatTypeId: 4,
        owner: "Наталья",
        mass: 4.4,
        date: "2025-01-30",
        colorId: 1,
        locationTypeId: 2,
        breedTypeId: 12,
        softness: "жёсткая",
        breadness: false,
        bigeyedness: 6,
        stars: 5
    },
    {
        id: 11,
        name: "Маркиз",
        shortName: "Марк",
        coatTypeId: 2,
        owner: "Виктор",
        mass: 5.8,
        date: "2025-03-18",
        colorId: 20,
        locationTypeId: 1,
        breedTypeId: 13,
        softness: "мягкая",
        breadness: true,
        bigeyedness: 8,
        stars: 5
    },
    {
        id: 12,
        name: "Ася",
        shortName: "Ася",
        coatTypeId: 5,
        owner: "Ирина",
        mass: 2.9,
        date: "2025-02-08",
        colorId: 14,
        locationTypeId: 1,
        breedTypeId: 14,
        softness: "без шерсти",
        breadness: false,
        bigeyedness: 10,
        stars: 5
    },
    {
        id: 13,
        name: "Леопольд",
        shortName: "Лео",
        coatTypeId: 1,
        owner: "Алексей",
        mass: 6.3,
        date: "2025-04-05",
        colorId: 18,
        locationTypeId: 2,
        breedTypeId: 15,
        softness: "очень мягкая",
        breadness: true,
        bigeyedness: 7,
        stars: 5
    },
    {
        id: 14,
        name: "Клео",
        shortName: "Клео",
        coatTypeId: 3,
        owner: "Татьяна",
        mass: 4.1,
        date: "2025-03-22",
        colorId: 6,
        locationTypeId: 1,
        breedTypeId: 2,
        softness: "средняя",
        breadness: false,
        bigeyedness: 6,
        stars: 5
    },
    {
        id: 15,
        name: "Пушок",
        shortName: "Пуш",
        coatTypeId: 2,
        owner: "Михаил",
        mass: 5.0,
        date: "2025-01-12",
        colorId: 7,
        locationTypeId: 1,
        breedTypeId: 5,
        softness: "мягкая",
        breadness: true,
        bigeyedness: 8,
        stars: 5
    },
    {
        id: 16,
        name: "Жорик",
        shortName: "Жора",
        coatTypeId: 4,
        owner: "Людмила",
        mass: 5.6,
        date: "2025-02-27",
        colorId: 12,
        locationTypeId: 2,
        breedTypeId: 1,
        softness: "жёсткая",
        breadness: false,
        bigeyedness: 5,
        stars: 5
    },
    {
        id: 17,
        name: "Ночка",
        shortName: "Ночь",
        coatTypeId: 1,
        owner: "Григорий",
        mass: 4.0,
        date: "2025-03-30",
        colorId: 16,
        locationTypeId: 2,
        breedTypeId: 6,
        softness: "очень мягкая",
        breadness: true,
        bigeyedness: 9,
        stars: 5
    },
    {
        id: 18,
        name: "Симба",
        shortName: "Сим",
        coatTypeId: 3,
        owner: "Ксения",
        mass: 5.3,
        date: "2025-04-07",
        colorId: 19,
        locationTypeId: 1,
        breedTypeId: 7,
        softness: "средняя",
        breadness: true,
        bigeyedness: 7,
        stars: 5
    },
    {
        id: 19,
        name: "Дуся",
        shortName: "Дуся",
        coatTypeId: 2,
        owner: "Павел",
        mass: 3.7,
        date: "2025-01-19",
        colorId: 13,
        locationTypeId: 2,
        breedTypeId: 10,
        softness: "мягкая",
        breadness: false,
        bigeyedness: 8,
        stars: 5
    },
    {
        id: 20,
        name: "Том",
        shortName: "Том",
        coatTypeId: 5,
        owner: "Вера",
        mass: 3.3,
        date: "2025-02-11",
        colorId: 10,
        locationTypeId: 2,
        breedTypeId: 9,
        softness: "без шерсти",
        breadness: true,
        bigeyedness: 10,
        stars: 5
    }
];

export { catColors, catCoatTypes, catLocationType, catBreeds, cats }